export const icon = {
  432: require('./432.png'),
  Home432: require('./432Home.png'),
  Avatar: require('./Avatar.png'),
  locoksmithIcon: require('./432icon.png'),
  collective: require('./Collective.png'),
  logo: require('./logo.png'),
  password: require('./Password.png'),
  email: require('./Email.png'),
  userIcon: require('./UserIcon.png'),
  dob: require('./Dob.png'),
  facebook: require('./Facebook.png'),
  instagram: require('./Instagram.png'),
  linkdin: require('./Linkedin.png'),
  twitter: require('./Twitter.png'),
  backButton: require('./BackButton.png'),
  userAvatar: require('./UserAvatar.png'),
  spaceImageShip: require('./SpaceImageShip.png'),
  play: require('./Play.png'),
};
